module.exports = [
  {
    id: 'USI7824yad77adywef',
    name: 'Dicoding',
    year: '2020',
    author: 'someone',
    summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt, veniamvoluptatum dignissimos delectus excepturi similique.',
    publisher: '-',
    pageCount: 50,
    readPage: 25,
    reading: true,
    finished: false,
    insertedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'USIu098adn89u',
    name: 'dicoding book',
    year: '2020',
    author: 'someone',
    summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt, veniamvoluptatum dignissimos delectus excepturi similique.',
    publisher: '-',
    pageCount: 50,
    readPage: 25,
    reading: false,
    finished: false,
    insertedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'USIoidf89ewhew87u',
    name: 'Booknya siapa',
    year: '2020',
    author: 'someone',
    summary: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt, veniamvoluptatum dignissimos delectus excepturi similique.',
    publisher: '-',
    pageCount: 50,
    readPage: 25,
    reading: false,
    finished: false,
    insertedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
